name: "Workflow Doc"
description: "A utility for generating documentation for a GitHub Actions workflow"
inputs:
  dir-or-file-path:
    description: |
      Path to workflow which should be analyzed for documentation generation.
    required: true
  output-dir:
    description: |
      The directory to save the generated workflow doc file.
    required: true
outputs:
  path-to-generated-doc:
    description: |
      Path to the generated workflow documentation.
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - generate
    - ${{ inputs.dir-or-file-path }}
    - "--output-dir"
    - ${{ inputs.output-dir }}
